title: Congatudo
description: >-
  Open source cloud replacement for Conga vacuum robots enabling local-only operation
baseurl: ""
url: https://congatudo.cloud
github_username: congatudo

plugins:
  - jekyll-seo-tag
collections:
  pages:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
